version: "3"

services:
    '2022':
        image: christiangroeber/php-server:7.4.2
        container_name: '2022'
        ports:
            - '86:80'
        volumes: 
            - ./:/var/www/html